sonar.projectKey=devsecops-pipeline_secure-delivery-api
sonar.projectName=secure-delivery-api
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
